/**
 * Unit tests for PLY header parsing and asset-kind classification.
 *
 * All tests work with synthetic ASCII PLY header strings encoded to
 * ArrayBuffers — no real binary assets are required.
 */

import { describe, it, expect } from "vitest";
import { parsePlyHeader, detectPlyKind } from "../classify";

// ── Helpers ──────────────────────────────────────────────────────────────────

/**
 * Encode a PLY header string to an ArrayBuffer.
 * The header string must end with "end_header\n" to be valid.
 */
function headerToBuffer(header: string): ArrayBuffer {
  return new TextEncoder().encode(header).buffer;
}

// ── Sample headers ────────────────────────────────────────────────────────────

const MESH_HEADER = [
  "ply",
  "format ascii 1.0",
  "comment generated by test",
  "element vertex 4",
  "property float x",
  "property float y",
  "property float z",
  "element face 2",
  "property list uchar int vertex_indices",
  "end_header",
  "",
].join("\n");

const POINT_CLOUD_HEADER = [
  "ply",
  "format ascii 1.0",
  "element vertex 1000",
  "property float x",
  "property float y",
  "property float z",
  "property uchar red",
  "property uchar green",
  "property uchar blue",
  "end_header",
  "",
].join("\n");

const GAUSSIAN_SPLAT_SH_HEADER = [
  "ply",
  "format binary_little_endian 1.0",
  "comment 3D Gaussian Splat",
  "element vertex 50000",
  "property float x",
  "property float y",
  "property float z",
  "property float f_dc_0",
  "property float f_dc_1",
  "property float f_dc_2",
  "property float scale_0",
  "property float scale_1",
  "property float scale_2",
  "property float rot_0",
  "property float rot_1",
  "property float rot_2",
  "property float rot_3",
  "property float opacity",
  "end_header",
  "",
].join("\n");

const GAUSSIAN_SPLAT_SCALE_ROT_HEADER = [
  "ply",
  "format binary_little_endian 1.0",
  "element vertex 30000",
  "property float x",
  "property float y",
  "property float z",
  "property float scale_0",
  "property float scale_1",
  "property float scale_2",
  "property float rot_0",
  "property float rot_1",
  "property float rot_2",
  "property float rot_3",
  "property float opacity",
  "end_header",
  "",
].join("\n");

// ── parsePlyHeader tests ──────────────────────────────────────────────────────

describe("parsePlyHeader", () => {
  it("parses a mesh PLY header correctly", () => {
    const header = parsePlyHeader(headerToBuffer(MESH_HEADER));

    expect(header.format).toBe("ascii");
    expect(header.comments).toEqual(["generated by test"]);
    expect(header.elements).toHaveLength(2);

    const vertex = header.elements[0];
    expect(vertex.name).toBe("vertex");
    expect(vertex.count).toBe(4);
    expect(vertex.properties.map((p) => p.name)).toEqual(["x", "y", "z"]);

    const face = header.elements[1];
    expect(face.name).toBe("face");
    expect(face.count).toBe(2);
    expect(face.properties[0].isList).toBe(true);
    expect(face.properties[0].name).toBe("vertex_indices");
  });

  it("parses a point-cloud PLY header correctly", () => {
    const header = parsePlyHeader(headerToBuffer(POINT_CLOUD_HEADER));

    expect(header.format).toBe("ascii");
    expect(header.elements).toHaveLength(1);

    const vertex = header.elements[0];
    expect(vertex.name).toBe("vertex");
    expect(vertex.count).toBe(1000);
    expect(vertex.properties.map((p) => p.name)).toEqual([
      "x",
      "y",
      "z",
      "red",
      "green",
      "blue",
    ]);
  });

  it("parses a Gaussian-splat PLY header (SH convention) correctly", () => {
    const header = parsePlyHeader(headerToBuffer(GAUSSIAN_SPLAT_SH_HEADER));

    expect(header.format).toBe("binary_little_endian");
    const vertex = header.elements[0];
    expect(vertex.count).toBe(50000);
    const propNames = vertex.properties.map((p) => p.name);
    expect(propNames).toContain("f_dc_0");
    expect(propNames).toContain("opacity");
  });

  it("records headerLength that points past end_header", () => {
    const raw = POINT_CLOUD_HEADER;
    const header = parsePlyHeader(headerToBuffer(raw));
    // headerLength must be > 0 and ≤ total buffer byte length.
    expect(header.headerLength).toBeGreaterThan(0);
    const totalBytes = new TextEncoder().encode(raw).byteLength;
    expect(header.headerLength).toBeLessThanOrEqual(totalBytes);
    // The byte just before headerLength should be within the header text.
    const slice = new TextDecoder().decode(
      new TextEncoder().encode(raw).slice(0, header.headerLength),
    );
    expect(slice).toContain("end_header");
  });

  it("throws when the buffer does not start with 'ply' magic", () => {
    const bad = headerToBuffer(MESH_HEADER.replace(/^ply/, "xyz"));
    expect(() => parsePlyHeader(bad)).toThrow(/ply/i);
  });

  it("throws when end_header is missing", () => {
    const incomplete = headerToBuffer(
      "ply\nformat ascii 1.0\nelement vertex 1\n",
    );
    expect(() => parsePlyHeader(incomplete)).toThrow(/end_header/i);
  });
});

// ── detectPlyKind tests ───────────────────────────────────────────────────────

describe("detectPlyKind", () => {
  it("classifies PLY with element face as 'mesh'", () => {
    const header = parsePlyHeader(headerToBuffer(MESH_HEADER));
    expect(detectPlyKind(header)).toBe("mesh");
  });

  it("classifies vertex-only x,y,z,r,g,b PLY as 'pointCloud'", () => {
    const header = parsePlyHeader(headerToBuffer(POINT_CLOUD_HEADER));
    expect(detectPlyKind(header)).toBe("pointCloud");
  });

  it("classifies Gaussian-splat (SH: f_dc_0) PLY as 'gaussianSplat'", () => {
    const header = parsePlyHeader(headerToBuffer(GAUSSIAN_SPLAT_SH_HEADER));
    expect(detectPlyKind(header)).toBe("gaussianSplat");
  });

  it("classifies Gaussian-splat (scale_0+rot_0+opacity) PLY as 'gaussianSplat'", () => {
    const header = parsePlyHeader(
      headerToBuffer(GAUSSIAN_SPLAT_SCALE_ROT_HEADER),
    );
    expect(detectPlyKind(header)).toBe("gaussianSplat");
  });

  it("classifies a face element with count=0 as 'pointCloud' (no renderable faces)", () => {
    const headerStr = [
      "ply",
      "format ascii 1.0",
      "element vertex 100",
      "property float x",
      "property float y",
      "property float z",
      "element face 0",
      "property list uchar int vertex_indices",
      "end_header",
      "",
    ].join("\n");
    const header = parsePlyHeader(headerToBuffer(headerStr));
    expect(detectPlyKind(header)).toBe("pointCloud");
  });
});
